
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Traceback (most recent call last):
  File "/home/users/delon/LensQuEst/dev/combine_RDN0.py", line 185, in <module>
    with open(RDN0_fname,"rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/oak/stanford/orgs/kipac/users/delon/LensQuEst/RDN0-in_data-500.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/delon/LensQuEst/dev/combine_RDN0.py", line 188, in <module>
    assert(1==0)
AssertionError
